server:
  servlet:
    context-path: /stock
  port: 8080

spring:
  application:
    name: stock-client
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  redis:
    #redis数据库索引(默认为0)
    database: 1
    #redis服务器地址
    host: localhost
    #redis服务器连接端口
    port: 6379
    #redis连接密码1
    password:
    timeout: 8000
    jedis:
      pool:
        max-active: 300
        max-wait: 1ms
        min-idle: 300
  data:
    mongodb:
      host: 127.0.0.1


stock:
  serverHost: http://114.55.140.140:8111/v1/